[package]
name = "rudoku"
version = "0.1.0"
edition = "2018"
authors = ["Nikhil T R <nikhiltr42@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
